### ISSUE TITLE
AMI deprecation step fails when `skip_create_ami` is true

### ISSUE THREAD

**Issue by sc250024** [hashicorp/packer-plugin-amazon#224]
#### Overview of the Issue

Using the newest version of Packer and the AWS EBS plugin, the EBS plugin spews out an error that begins with `unexpected EOF`, but is really related to the `stepEnableDeprecation` call.

~~I _think_ the error might be related to the fact that the AMI I am using as a base (`base-ami`) already has the `DeprecationTime` field set. So when this new AMI tries to do the same, it receives an error.~~

_**UPDATE:**_ I'll try and isolate the root issue with test Packer configs.

```
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: panic: interface conversion: interface {} is nil, not map[string]string
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: goroutine 369 [running]:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*stepEnableDeprecation).Run(0xc000399290, {0x24730f5, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/step_enable_deprecation.go:25 +0x3ae
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc000562e70, {0x27e4848, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/multistep/basic_runner.go:70 +0x2fe
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*Builder).Run(0xc0003d8a80, {0x27e4848, 0xc0008140c0}, {0x27ebdf0, 0xc0005623c0}, {0x27c2b60, 0xc0004360a0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/builder.go:410 +0x268c
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc0001410c0, 0x6ae040, 0xc0006ae020)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/rpc/builder.go:117 +0x1e3
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.call({0xc00009c660, 0xc00000e208, 0x13}, {0x246cd79, 0x4}, {0xc000571ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:556 +0x845
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.Call({0xc00009c660, 0xc00000e208, 0xc00007f200}, {0xc000474ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:339 +0xc5
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: net/rpc.(*service).call(0xc000141100, 0xc000047858, 0x0, 0xc000046ca0, 0xc000054700, 0x18bb985, {0x20246c0, 0xc0006ae01c, 0x18bb906}, {0x1fe6fe0, ...}, ...)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:377 +0x239
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:474 +0x405
```

#### Reproduction Steps

I'm still trying to isolate the cause of this problem. This does not happen when I build a base AMI using the Ubuntu 22.04 LTS image as a source. However, it *does* happen when I use the base AMI as a source.

In other words:

```
Ubuntu 22.04 - OK > Base AMI - Not OK -> New AMI
```

### Plugin and Packer version

- Packer version: `Packer v1.8.1`
- The `packer-plugin-amazon` version: `packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64`

### Simplified Packer Buildfile

See ***Reproduction Steps*** above.

### Operating system and Environment details

- OS `uname`: `Darwin <machine-id> 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64` => aka *macOS Big Sur 11.6.6*

### Log Fragments and crash.log files

<details>
<summary>Panic error output</summary>

```
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: panic: interface conversion: interface {} is nil, not map[string]string
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: goroutine 369 [running]:
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*stepEnableDeprecation).Run(0xc000399290, {0x24730f5, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/step_enable_deprecation.go:25 +0x3ae
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/multistep.(*BasicRunner).Run(0xc000562e70, {0x27e4848, 0xc0008140c0}, {0x27e4df8, 0xc000562db0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/multistep/basic_runner.go:70 +0x2fe
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-amazon/builder/ebs.(*Builder).Run(0xc0003d8a80, {0x27e4848, 0xc0008140c0}, {0x27ebdf0, 0xc0005623c0}, {0x27c2b60, 0xc0004360a0})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-amazon/builder/ebs/builder.go:410 +0x268c
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: github.com/hashicorp/packer-plugin-sdk/rpc.(*BuilderServer).Run(0xc0001410c0, 0x6ae040, 0xc0006ae020)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	github.com/hashicorp/packer-plugin-sdk@v0.2.12/rpc/builder.go:117 +0x1e3
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.call({0xc00009c660, 0xc00000e208, 0x13}, {0x246cd79, 0x4}, {0xc000571ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:556 +0x845
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: reflect.Value.Call({0xc00009c660, 0xc00000e208, 0xc00007f200}, {0xc000474ef8, 0x3, 0x3})
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	reflect/value.go:339 +0xc5
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: net/rpc.(*service).call(0xc000141100, 0xc000047858, 0x0, 0xc000046ca0, 0xc000054700, 0x18bb985, {0x20246c0, 0xc0006ae01c, 0x18bb906}, {0x1fe6fe0, ...}, ...)
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:377 +0x239
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: created by net/rpc.(*Server).ServeCodec
2022/06/01 16:01:38 packer-plugin-amazon_v1.1.0_x5.0_darwin_amd64 plugin: 	net/rpc/server.go:474 +0x405
```

</details>

- GitHub gist of the full build log with trace logging: https://gist.github.com/sc250024/a02ab45677f5f34f1ceddbc90f679541

**Comment by nywilken** [comment]
Thanks for bubbling this up. It looks like you are skipping the ami creation in the `skip_create_ami` within the Packer config. But then trying to set a deprecation time on an ami that doesn't exist, which is why you are getting an error. This is not a supported use case. 

If you could provide us with a redacted configuration file on what you are trying to do, it will help us better understand the end goal. 

That said, there is a crash happening that we will address separately for the next release.

**Comment by sc250024** [comment]
> Thanks for bubbling this up. It looks like you are skipping the ami creation in the `skip_create_ami` within the Packer config. But then trying to set a deprecation time on an ami that doesn't exist, which is why you are getting an error. This is not a supported use case.
> 
> If you could provide us with a redacted configuration file on what you are trying to do, it will help us better understand the end goal.
> 
> That said, there is a crash happening that we will address separately for the next release.

@nywilken Yes, I figured that out today actually, thank you for the insight as well. I will update the title to be more descriptive of the error. Do you still need an HCL document example?

**Comment by lbajolet-hashicorp** [comment]
Hi @sc250024, while this could be considered a bug, I don't think we should silently forego running the deprecation step if there's a `skip_create_ami` directive, but instead point out that something doesn't add up in the configs.

Right now it panics, which should definitely not be the case, the tool should gracefully stop, while pointing out that the specs cannot work out as it stands.
